'use client';

import React, { useState } from 'react';
import { Copy, Check, Printer, FileText, HelpCircle, AlertOctagon, Scale } from 'lucide-react';
import type { AnalysisResult } from '@/lib/types';

interface LawyerPrepKitProps {
  analysis: AnalysisResult;
}

export default function LawyerPrepKit({ analysis }: LawyerPrepKitProps) {
  const [copied, setCopied] = useState(false);

  const { summary, attorneyQuestions, clauses } = analysis;
  const highRiskClauses = clauses.filter((c) => c.riskLevel === 'HIGH' || c.riskLevel === 'MEDIUM');

  const handleCopyDocket = () => {
    const docketText = `
JURISBRIDGE AI - ATTORNEY CONSULTATION DOCKET
=====================================================

EXECUTIVE SUMMARY:
${summary}

HIGH & MEDIUM RISK CLAUSES REQUIRING REVIEW:
${highRiskClauses
  .map(
    (c, idx) =>
      `\n[${idx + 1}] Category: ${c.category} (Risk: ${c.riskLevel})\nOriginal Text: "${c.originalText}"\nExplanation: ${c.explanation}\nSuggested Revision: ${c.suggestedRevision || 'N/A'}`
  )
  .join('\n')}

PINPOINTED QUESTIONS TO ASK ATTORNEY:
${attorneyQuestions.map((q, idx) => `${idx + 1}. ${q}`).join('\n')}

=====================================================
Generated by JurisBridge AI (Informational Tool)
`;

    navigator.clipboard.writeText(docketText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <section
      aria-labelledby="lawyer-prep-kit-heading"
      className="bg-slate-900/90 backdrop-blur-md border border-indigo-900/40 rounded-xl p-6 shadow-lg space-y-6"
    >
      {/* Outer Header with Print/Copy buttons */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h2
            id="lawyer-prep-kit-heading"
            className="text-xl font-bold text-white flex items-center gap-2"
          >
            <Scale className="h-6 w-6 text-indigo-400" aria-hidden="true" />
            <span>Attorney Consultation Docket</span>
          </h2>
          <p className="text-sm text-slate-400 mt-1">
            Synthesized docket and pinpointed questions ready for legal counsel review
          </p>
        </div>

        {/* Action Buttons - Excluded from Print */}
        <div className="flex items-center gap-2 no-print print:hidden">
          <button
            onClick={handleCopyDocket}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 transition shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
            aria-label="Copy Attorney Docket to Clipboard"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-emerald-300" aria-hidden="true" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" aria-hidden="true" />
                <span>Copy Attorney Docket</span>
              </>
            )}
          </button>

          <button
            onClick={handlePrint}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 transition focus:outline-none focus:ring-2 focus:ring-slate-400"
            aria-label="Print Attorney Docket"
          >
            <Printer className="h-4 w-4 text-slate-300" aria-hidden="true" />
            <span>Print Docket</span>
          </button>
        </div>
      </div>

      {/* Dedicated Printable Docket Container */}
      <div id="printable-docket" className="space-y-6">
        {/* Printable Title Header */}
        <div className="hidden print:block border-b border-gray-300 pb-4 mb-4">
          <h1 className="text-2xl font-bold text-gray-900">JurisBridge AI - Legal Consultation Memorandum</h1>
          <p className="text-xs text-gray-600 mt-1">
            Generated analysis docket for attorney review &amp; legal consultation.
          </p>
        </div>

        {/* Executive Overview for Lawyer */}
        <div className="bg-slate-950/70 p-5 rounded-xl border border-slate-800 space-y-2 break-words">
          <h3 className="text-xs font-semibold text-indigo-300 uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="h-4 w-4 text-indigo-400" aria-hidden="true" />
            <span>Synthesized Case Overview</span>
          </h3>
          <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">{summary}</p>
        </div>

        {/* Checklist of Attorney Questions */}
        <div className="bg-slate-950/70 p-5 rounded-xl border border-slate-800 space-y-3 break-words">
          <h3 className="text-sm font-semibold text-amber-300 flex items-center gap-2">
            <HelpCircle className="h-4 w-4 text-amber-400" aria-hidden="true" />
            <span>Pinpointed Questions for Legal Counsel ({attorneyQuestions.length})</span>
          </h3>
          <ul className="space-y-2.5">
            {attorneyQuestions.map((q, idx) => (
              <li key={idx} className="flex items-start gap-3 bg-slate-900/60 p-3 rounded-lg border border-slate-800">
                <span className="flex shrink-0 items-center justify-center h-6 w-6 rounded-full bg-amber-950 text-amber-300 font-mono text-xs font-bold border border-amber-800">
                  {idx + 1}
                </span>
                <p className="text-sm text-slate-200 leading-snug pt-0.5">{q}</p>
              </li>
            ))}
          </ul>
        </div>

        {/* Flagged Risk Clauses Summary List */}
        {highRiskClauses.length > 0 && (
          <div className="bg-slate-950/70 p-5 rounded-xl border border-slate-800 space-y-3 break-words">
            <h3 className="text-sm font-semibold text-rose-300 flex items-center gap-2">
              <AlertOctagon className="h-4 w-4 text-rose-400" aria-hidden="true" />
              <span>Flagged Clauses Requiring Attorney Attention ({highRiskClauses.length})</span>
            </h3>
            <div className="space-y-3">
              {highRiskClauses.map((c) => (
                <div key={c.id} className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-800 text-xs sm:text-sm space-y-1.5">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-white">{c.category}</span>
                    <span
                      className={`px-2 py-0.5 rounded text-xs font-bold ${
                        c.riskLevel === 'HIGH'
                          ? 'bg-rose-950 text-rose-300 border border-rose-800'
                          : 'bg-amber-950 text-amber-300 border border-amber-800'
                      }`}
                    >
                      {c.riskLevel} RISK
                    </span>
                  </div>
                  <p className="text-slate-400 font-mono italic text-xs whitespace-pre-wrap">&quot;{c.originalText}&quot;</p>
                  <p className="text-slate-300 font-medium">{c.explanation}</p>
                  {c.suggestedRevision && (
                    <p className="text-indigo-300 text-xs font-mono pt-1">
                      <strong className="font-semibold text-indigo-200">Suggested Revision: </strong>
                      {c.suggestedRevision}
                    </p>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Printable Legal Notice Footer */}
        <div className="hidden print:block pt-4 border-t border-gray-300 text-xs text-gray-500">
          Disclaimer: JurisBridge AI provides educational analysis and consultation preparation assistance, not professional legal counsel.
        </div>
      </div>
    </section>
  );
}
